### ISSUE TITLE
Build errors with Debian / Python 3.7

### ISSUE THREAD

**Issue by shoeffner** [rock-learning/bolero#104]
I am trying to install bolero using bootstrap_bolero.sh inside a docker container.
The base image is [`python:3.7-stretch`](https://github.com/docker-library/python/blob/master/3.7/stretch/Dockerfile).

The commands I run to install bolero are:
```bash
apt-get update
apt-get install -y sudo
pip install pyyaml cython numpy nose 
wget https://raw.githubusercontent.com/rock-learning/bolero/master/bootstrap_bolero.sh
chmod +x bootstrap_bolero.sh
# Optionally tried to remove sudo, as the docker user is root anyways
# sed -i 's/sudo //g' bootstrap_bolero.sh
./bootstrap_bolero.sh
```
This seems to work fine (return code is 0), but in fact the output shows errors and bolero can not be imported after sourcing env.sh.
```
Errors:
 - configure: learning/bolero/include
 - configure: simulation/lib_manager
 - configure: base/cmake
 - configure: tools/configmaps
 - configure: learning/bolero/src/optimizer/cmaes_optimizer
 - configure: learning/bolero/src/bl_loader
 - configure: learning/bolero/src/environment/function_approximation
 - configure: learning/bolero/src/environment/mountain_car
 - configure: learning/bolero/src/environment/cec13_test_functions
 - configure: learning/bolero/src/optimizer/pso_optimizer
 - configure: learning/bolero/src/representation/promp
 - configure: learning/bolero/bolero/wrapper
 - configure: learning/bolero/src/representation/dmp
 - configure: learning/bolero/src/controller
 - configure: learning/bolero
Installed packages: 
[]
```

When trying to install by downloading the latest release from GitHub (https://github.com/rock-learning/bolero/releases/download/v1.0.0/bolero_release.zip), the install.sh runs some scripts which apparently are only Python 2 compatible, as they have print statements rather than using the print function, so that does not work well either.

Do you have any suggestions?

The full dockerfile is:
```Dockerfile
FROM python:3.7-stretch

RUN apt-get update \
    && apt-get install -y sudo \
    && pip install pyyaml cython numpy nose \
    && wget https://raw.githubusercontent.com/rock-learning/bolero/master/bootstrap_bolero.sh \
    && chmod +x bootstrap_bolero.sh \
#    && sed -i 's/sudo //g' bootstrap_bolero.sh \
    && ./bootstrap_bolero.sh

COPY entrypoint.sh /entrypoint.sh
WORKDIR ./bolero-dev
ENTRYPOINT ["/entrypoint.sh"]
CMD nosetests bolero -sv
```
with entrypoint.sh being:
```bash
#!/bin/bash
set -e

source ./env.sh
exec "$@"
```
